// GENERATED by forum-core/examples/generate_contracts.rs. Do not edit.
// UTF-8 offsets are bytes, never JavaScript string indices. Validate wire data before use.
export const SCHEMA_VERSION = 1 as const;

export type AudioGap = {
  "audio": AudioRange;
  "gap_id": string;
  "reason": string;
  "recoverable": boolean;
  "track_id": string;
};

export type AudioGapEvent = {
  "event_id": string;
  "message_id": string;
  "payload": AudioGap;
  "producer": Producer;
  "room_id": string;
  "schema_version": 1;
  "session_id": string;
  "type": "audio.gap";
};

export type AudioRange = {
  "end_ms": number;
  "end_sample": number;
  "sample_rate": number;
  "start_ms": number;
  "start_sample": number;
};

export type CaptureSegmentClosed = {
  "audio": AudioRange;
  "recording_ref"?: string | null;
  "segment_id": string;
  "track_id": string;
};

export type CaptureSegmentClosedEvent = {
  "event_id": string;
  "message_id": string;
  "payload": CaptureSegmentClosed;
  "producer": Producer;
  "room_id": string;
  "schema_version": 1;
  "session_id": string;
  "type": "audio.segment_closed";
};

export type CaptureStopped = {
  "manifest_sha256": string;
  "tracks": Array<TrackSeal>;
};

export type CaptureStoppedEvent = {
  "event_id": string;
  "message_id": string;
  "payload": CaptureStopped;
  "producer": Producer;
  "room_id": string;
  "schema_version": 1;
  "session_id": string;
  "type": "session.capture_stopped";
};

export type CoverageIntent = {
  "direction_epoch": number;
  "end_utf8": number;
  "segment_id": string;
  "segment_revision": Revision;
  "start_utf8": number;
  "state": string;
  "target_language": string;
};

export type DirectionBoundary = {
  "configured_source_language": string;
  "start_sample": number;
  "track_id": string;
};

export type DirectionChanged = {
  "boundary"?: DirectionBoundary | null;
  "direction_epoch": number;
  "expected_epoch": number;
  "target_languages": Array<string>;
};

export type DirectionChangedEvent = {
  "event_id": string;
  "message_id": string;
  "payload": DirectionChanged;
  "producer": Producer;
  "room_id": string;
  "schema_version": 1;
  "session_id": string;
  "type": "translation.direction_changed";
};

export type EventType = "session.changed" | "audio.gap" | "session.capture_stopped" | "session.producer_sealed" | "session.producer_reconciled" | "session.transcript_sealed" | "translation.requested" | "translation.final" | "translation.failed" | "translation.direction_changed" | "audio.segment_closed" | "transcript.final" | "transcript.revised";

export type ForumEvent = CaptureSegmentClosedEvent | TranscriptFinalEvent | TranscriptRevisionEvent | SessionTransitionEvent | AudioGapEvent | CaptureStoppedEvent | ProducerSealEvent | ProducerReconciledEvent | TranscriptSealEvent | DirectionChangedEvent | TranslationRequestedEvent | TranslationFinalEvent | TranslationFailedEvent;

export type IncompleteSegment = {
  "audio": AudioRange;
  "reason"?: string | null;
  "recording_ref"?: string | null;
  "segment_id": string;
  "status"?: TranscriptStatus | null;
  "track_id": string;
};

export type OutboxMessage = {
  "body": unknown;
  "event_type": string;
  "message_id": string;
  "session_id": string;
  "store_seq": number;
};

export type PageKey = {
  "segment_id": string;
  "start_ms": number;
  "track_id": string;
};

export type Producer = {
  "name": string;
  "run_id": string;
  "seq": number;
};

export type ProducerReconciled = {
  "evidence": ProducerRecoveryEvidence;
  "final_seq": number;
  "producer_run_id": string;
};

export type ProducerReconciledEvent = {
  "event_id": string;
  "message_id": string;
  "payload": ProducerReconciled;
  "producer": Producer;
  "room_id": string;
  "schema_version": 1;
  "session_id": string;
  "type": "session.producer_reconciled";
};

export type ProducerRecoveryEvidence = {
  "capture_manifest_sha256": string;
  "outbox_replayed": boolean;
  "owned_process_exited": boolean;
  "reason": string;
};

export type ProducerSeal = {
  "final_seq": number;
  "producer_run_id": string;
  "segment_ids": Array<string>;
};

export type ProducerSealEvent = {
  "event_id": string;
  "message_id": string;
  "payload": ProducerSeal;
  "producer": Producer;
  "room_id": string;
  "schema_version": 1;
  "session_id": string;
  "type": "session.producer_sealed";
};

export type Receipt = {
  "duplicate": boolean;
  "message_id": string;
  "store_seq": number;
};

export type RecoveryRevision = {
  "next_revision"?: Revision | null;
  "segment_id": string;
  "terminal": boolean;
};

export type RecoverySegment = {
  "audio": AudioRange;
  "next_revision": Revision;
  "previous_status"?: TranscriptStatus | null;
  "reason"?: string | null;
  "recording_ref"?: string | null;
  "segment_id": string;
  "track_id": string;
};

export type Revision = number;

export type RevisionOrigin = {
  "kind": "asr";
} | {
  "base_revision": Revision;
  "kind": "human";
  "operator_id": string;
  "reason": string;
};

export type SessionExport = {
  "gaps": Array<AudioGap>;
  "snapshot": SessionSnapshot;
  "sources": Array<SnapshotItem>;
  "status": SessionStatus;
  "translations": Array<TranslationRecord>;
};

export type SessionSnapshot = {
  "cursor": number;
  "incomplete": Array<IncompleteSegment>;
  "session": SessionSpec;
  "transcript": Array<TranscriptRecord>;
};

export type SessionSpec = {
  "event_id": string;
  "owner_device_id": string;
  "room_id": string;
  "session_id": string;
  "title": string;
};

export type SessionState = "created" | "preparing" | "ready" | "recording" | "stopping" | "draining" | "completed" | "interrupted";

export type SessionStatus = {
  "capture_stopped": boolean;
  "direction_epoch": number;
  "incomplete": boolean;
  "session_id": string;
  "state": SessionState;
  "state_seq": number;
  "target_languages": Array<string>;
  "transcript_sealed": boolean;
};

export type SessionSummary = {
  "cursor": number;
  "segment_count": number;
  "session": SessionSpec;
  "status": SessionStatus;
  "translation_pending": number;
};

export type SessionTransition = {
  "expected_state": SessionState;
  "next_state": SessionState;
  "reason": string;
};

export type SessionTransitionEvent = {
  "event_id": string;
  "message_id": string;
  "payload": SessionTransition;
  "producer": Producer;
  "room_id": string;
  "schema_version": 1;
  "session_id": string;
  "type": "session.changed";
};

export type SnapshotItem = {
  "audio": AudioRange;
  "recording_ref"?: string | null;
  "segment_id": string;
  "track_id": string;
  "transcript"?: TranscriptRecord | null;
};

export type SnapshotPage = {
  "cursor": number;
  "items": Array<SnapshotItem>;
  "next_after"?: PageKey | null;
  "session": SessionSpec;
  "status": SessionStatus;
};

export type SourceSpan = {
  "end_utf8": number;
  "quote": string;
  "segment_id": string;
  "segment_revision": Revision;
  "start_utf8": number;
};

export type TrackKind = "mic" | "system" | "room_mix" | "replay";

export type TrackSeal = {
  "final_sample": number;
  "segment_ids": Array<string>;
  "track_id": string;
};

export type TrackSpec = {
  "kind": TrackKind;
  "sample_rate": number;
  "session_id": string;
  "track_id": string;
};

export type TranscriptFinal = {
  "audio": AudioRange;
  "backend": string;
  "configured_source_language": string;
  "detected_language"?: string | null;
  "direction_epoch": number;
  "model_manifest_id": string;
  "reason"?: string | null;
  "revision": Revision;
  "segment_id": string;
  "speaker_id"?: string | null;
  "status": TranscriptStatus;
  "target_languages": Array<string>;
  "text": string;
  "track_id": string;
};

export type TranscriptFinalEvent = {
  "event_id": string;
  "message_id": string;
  "payload": TranscriptFinal;
  "producer": Producer;
  "room_id": string;
  "schema_version": 1;
  "session_id": string;
  "type": "transcript.final";
};

export type TranscriptRecord = {
  "created_seq": number;
  "origin": RevisionOrigin;
  "payload": TranscriptFinal;
  "session_id": string;
};

export type TranscriptRevision = {
  "expected_revision": Revision;
  "operator_id": string;
  "reason": string;
  "segment_id": string;
  "text": string;
};

export type TranscriptRevisionEvent = {
  "event_id": string;
  "message_id": string;
  "payload": TranscriptRevision;
  "producer": Producer;
  "room_id": string;
  "schema_version": 1;
  "session_id": string;
  "type": "transcript.revised";
};

export type TranscriptSeal = {
  "capture_manifest_sha256": string;
};

export type TranscriptSealEvent = {
  "event_id": string;
  "message_id": string;
  "payload": TranscriptSeal;
  "producer": Producer;
  "room_id": string;
  "schema_version": 1;
  "session_id": string;
  "type": "session.transcript_sealed";
};

export type TranscriptStatus = "success" | "empty" | "failed";

export type TranslationFailed = {
  "attempt": number;
  "code": string;
  "direction_epoch": number;
  "reason": string;
  "revision": Revision;
  "translation_id": string;
};

export type TranslationFailedEvent = {
  "event_id": string;
  "message_id": string;
  "payload": TranslationFailed;
  "producer": Producer;
  "room_id": string;
  "schema_version": 1;
  "session_id": string;
  "type": "translation.failed";
};

export type TranslationFinal = {
  "attempt": number;
  "backend": string;
  "direction_epoch": number;
  "elapsed_ms": number;
  "model_manifest_id": string;
  "revision": Revision;
  "status": TranslationStatus;
  "text": string;
  "translation_id": string;
};

export type TranslationFinalEvent = {
  "event_id": string;
  "message_id": string;
  "payload": TranslationFinal;
  "producer": Producer;
  "room_id": string;
  "schema_version": 1;
  "session_id": string;
  "type": "translation.final";
};

export type TranslationPage = {
  "cursor": number;
  "items": Array<TranslationRecord>;
  "next_after"?: TranslationPageKey | null;
};

export type TranslationPageKey = {
  "created_seq": number;
  "translation_id": string;
};

export type TranslationRecord = {
  "created_seq": number;
  "error"?: string | null;
  "request": TranslationRequested;
  "result"?: TranslationFinal | null;
  "session_id": string;
  "state": string;
  "text"?: string | null;
  "updated_seq": number;
};

export type TranslationRequested = {
  "attempt": number;
  "backend": string;
  "direction_epoch": number;
  "input_text": string;
  "model_manifest_id": string;
  "normalization_version": string;
  "revision": Revision;
  "source_spans": Array<SourceSpan>;
  "target_language": string;
  "translation_id": string;
};

export type TranslationRequestedEvent = {
  "event_id": string;
  "message_id": string;
  "payload": TranslationRequested;
  "producer": Producer;
  "room_id": string;
  "schema_version": 1;
  "session_id": string;
  "type": "translation.requested";
};

export type TranslationStatus = "final" | "passthrough";

export type TranslationWork = {
  "configured_source_language": string;
  "detected_language"?: string | null;
  "direction_epoch": number;
  "source_span": SourceSpan;
  "target_language": string;
};
