// GENERATED by forum-core/examples/generate_contracts.rs. Do not edit.
// UTF-8 offsets are bytes, never JavaScript string indices. Validate wire data before use.
export const SCHEMA_VERSION = 1 as const;

export type AnalysisCheckpoint = {
  "attempt": number;
  "effective_config_hash": string;
  "input_sha256": string;
  "job_id": string;
  "result": unknown;
  "result_sha256": string;
  "snapshot_sha256": string;
  "step_index": number;
};

export type AnalysisClaim = {
  "assignee"?: string | null;
  "claim_id": string;
  "due"?: string | null;
  "evidence": Array<AnalysisEvidence>;
  "grounding": GroundingStatus;
  "kind": ClaimKind;
  "text": string;
};

export type AnalysisConfig = {
  "effective_config_hash": string;
  "generation": unknown;
  "model_manifest_id": string;
  "model_profile": string;
  "profile_id": string;
  "profile_sha256": string;
  "profile_version": string;
  "projection_policy_hash": string;
  "prompt_sha256": string;
  "prompt_version": string;
};

export type AnalysisCoverage = {
  "units": Array<CoverageUnit>;
};

export type AnalysisEvidence = {
  "kind": "source";
  "session_id": string;
  "span": SourceSpan;
} | {
  "artifact_id": string;
  "end_utf8": number;
  "kind": "artifact";
  "quote": string;
  "revision": Revision;
  "start_utf8": number;
};

export type AnalysisEvidenceView = {
  "current": boolean;
  "quote": string;
  "text": string;
};

export type AnalysisJob = {
  "attempt": number;
  "automatic": boolean;
  "budget_ms": number;
  "config": AnalysisConfig;
  "created_at_ms": number;
  "deadline_at_ms": number;
  "error"?: string | null;
  "event_id": string;
  "job_id": string;
  "kind": AnalysisKind;
  "max_attempts": number;
  "progress": AnalysisProgress;
  "request_id": string;
  "result"?: ArtifactRef | null;
  "session_ids": Array<string>;
  "snapshot_id": string;
  "snapshot_sha256": string;
  "started_at_ms"?: number | null;
  "state": AnalysisJobState;
};

export type AnalysisJobPage = {
  "cursor": number;
  "items": Array<AnalysisJob>;
  "next_after"?: AnalysisPageKey | null;
};

export type AnalysisJobState = "queued" | "waiting" | "running" | "cancel_requested" | "cancelled" | "succeeded" | "succeeded_partial" | "failed" | "interrupted";

export type AnalysisKind = "insight" | "minutes" | "event_report" | "suggested_questions" | "redaction_review" | "closing_brief";

export type AnalysisPageKey = {
  "created_at_ms": number;
  "cursor": number;
  "id": string;
};

export type AnalysisProgress = {
  "completed_units": number;
  "phase": string;
  "total_units": number;
  "wait_reason"?: string | null;
};

export type AnalysisPublishedInput = {
  "artifact_id": string;
  "kind": AnalysisKind;
  "revision": Revision;
  "session_ids": Array<string>;
  "text": string;
  "title": string;
};

export type AnalysisResult = {
  "attempt": number;
  "content": ArtifactContent;
  "coverage": AnalysisCoverage;
  "effective_config_hash": string;
  "job_id": string;
  "schema_version": number;
  "snapshot_id": string;
  "snapshot_sha256": string;
};

export type AnalysisSection = {
  "claims": Array<AnalysisClaim>;
  "heading": string;
  "topics"?: Array<AnalysisTopic>;
};

export type AnalysisSnapshot = {
  "effective_config_hash": string;
  "event_id": string;
  "input_complete": boolean;
  "input_cursor": number;
  "kind": AnalysisKind;
  "published_artifacts": Array<AnalysisPublishedInput>;
  "schema_version": number;
  "segments": Array<AnalysisSource>;
  "session_ids": Array<string>;
  "snapshot_id": string;
};

export type AnalysisSnapshotData = {
  "compact_json": string;
  "sha256": string;
  "snapshot": AnalysisSnapshot;
};

export type AnalysisSource = {
  "audio": AudioRange;
  "revision"?: Revision | null;
  "segment_id": string;
  "session_id": string;
  "speaker_id"?: string | null;
  "status"?: TranscriptStatus | null;
  "text": string;
};

export type AnalysisTopic = {
  "evidence": Array<AnalysisEvidence>;
  "label": string;
};

export type ArtifactContent = {
  "sections": Array<AnalysisSection>;
  "title": string;
};

export type ArtifactEdit = {
  "artifact_id": string;
  "content": ArtifactContent;
  "expected_revision": Revision;
  "operator_id": string;
  "reason": string;
};

export type ArtifactPage = {
  "cursor": number;
  "items": Array<ArtifactRecord>;
  "next_after"?: AnalysisPageKey | null;
};

export type ArtifactPublication = "private" | "published" | "hidden" | "withdrawn";

export type ArtifactPublishCommand = {
  "artifact_id": string;
  "evidence": Array<PublicEvidenceInput>;
  "expected_revision": Revision;
  "operator_id": string;
  "policy_hash": string;
  "reason": string;
  "reviewed_text": string;
  "reviewed_title": string;
};

export type ArtifactRecord = {
  "artifact_id": string;
  "config": AnalysisConfig;
  "content": ArtifactContent;
  "coverage": AnalysisCoverage;
  "coverage_complete": boolean;
  "created_at_ms": number;
  "event_id": string;
  "job_id": string;
  "kind": AnalysisKind;
  "operator_id"?: string | null;
  "publication": ArtifactPublication;
  "reason"?: string | null;
  "review": ArtifactReview;
  "revision": Revision;
  "session_ids": Array<string>;
  "snapshot_id": string;
  "validation": ArtifactValidation;
};

export type ArtifactRef = {
  "artifact_id": string;
  "revision": Revision;
};

export type ArtifactReview = "draft" | "approved" | "rejected";

export type ArtifactReviewCommand = {
  "artifact_id": string;
  "expected_revision": Revision;
  "operator_id": string;
  "reason": string;
  "review": ArtifactReview;
};

export type ArtifactValidation = "valid" | "needs_review" | "invalid" | "stale";

export type ArtifactVisibilityCommand = {
  "artifact_id": string;
  "expected_revision": Revision;
  "operator_id": string;
  "publication": ArtifactPublication;
  "reason": string;
};

export type AudioGap = {
  "audio": AudioRange;
  "gap_id": string;
  "reason": string;
  "recoverable": boolean;
  "track_id": string;
};

export type AudioGapEvent = {
  "event_id": string;
  "message_id": string;
  "payload": AudioGap;
  "producer": Producer;
  "room_id": string;
  "schema_version": 1;
  "session_id": string;
  "type": "audio.gap";
};

export type AudioRange = {
  "end_ms": number;
  "end_sample": number;
  "sample_rate": number;
  "start_ms": number;
  "start_sample": number;
};

export type CaptureSegmentClosed = {
  "audio": AudioRange;
  "recording_ref"?: string | null;
  "segment_id": string;
  "track_id": string;
};

export type CaptureSegmentClosedEvent = {
  "event_id": string;
  "message_id": string;
  "payload": CaptureSegmentClosed;
  "producer": Producer;
  "room_id": string;
  "schema_version": 1;
  "session_id": string;
  "type": "audio.segment_closed";
};

export type CaptureStopped = {
  "manifest_sha256": string;
  "tracks": Array<TrackSeal>;
};

export type CaptureStoppedEvent = {
  "event_id": string;
  "message_id": string;
  "payload": CaptureStopped;
  "producer": Producer;
  "room_id": string;
  "schema_version": 1;
  "session_id": string;
  "type": "session.capture_stopped";
};

export type ClaimKind = "fact" | "decision" | "action" | "risk" | "question" | "uncertainty";

export type CoverageIntent = {
  "direction_epoch": number;
  "end_utf8": number;
  "segment_id": string;
  "segment_revision": Revision;
  "start_utf8": number;
  "state": string;
  "target_language": string;
};

export type CoverageStatus = "processed" | "failed" | "ignored_empty";

export type CoverageTarget = {
  "kind": "source";
  "segment_id": string;
  "segment_revision"?: Revision | null;
} | {
  "artifact_id": string;
  "kind": "artifact";
  "revision": Revision;
};

export type CoverageUnit = {
  "end_utf8": number;
  "reason"?: string | null;
  "start_utf8": number;
  "status": CoverageStatus;
  "target": CoverageTarget;
};

export type CreateAnalysisJob = {
  "automatic": boolean;
  "budget_ms": number;
  "config": AnalysisConfig;
  "kind": AnalysisKind;
  "max_attempts": number;
  "request_id": string;
  "session_ids": Array<string>;
};

export type DirectionBoundary = {
  "configured_source_language": string;
  "start_sample": number;
  "track_id": string;
};

export type DirectionChanged = {
  "boundary"?: DirectionBoundary | null;
  "direction_epoch": number;
  "expected_epoch": number;
  "target_languages": Array<string>;
};

export type DirectionChangedEvent = {
  "event_id": string;
  "message_id": string;
  "payload": DirectionChanged;
  "producer": Producer;
  "room_id": string;
  "schema_version": 1;
  "session_id": string;
  "type": "translation.direction_changed";
};

export type EventType = "session.changed" | "audio.gap" | "session.capture_stopped" | "session.producer_sealed" | "session.producer_reconciled" | "session.transcript_sealed" | "translation.requested" | "translation.final" | "translation.failed" | "translation.direction_changed" | "audio.segment_closed" | "transcript.final" | "transcript.revised";

export type ForumEvent = CaptureSegmentClosedEvent | TranscriptFinalEvent | TranscriptRevisionEvent | SessionTransitionEvent | AudioGapEvent | CaptureStoppedEvent | ProducerSealEvent | ProducerReconciledEvent | TranscriptSealEvent | DirectionChangedEvent | TranslationRequestedEvent | TranslationFinalEvent | TranslationFailedEvent;

export type GroundingStatus = "cited" | "unsupported";

export type IncompleteSegment = {
  "audio": AudioRange;
  "reason"?: string | null;
  "recording_ref"?: string | null;
  "segment_id": string;
  "status"?: TranscriptStatus | null;
  "track_id": string;
};

export type OutboxMessage = {
  "body": unknown;
  "event_type": string;
  "message_id": string;
  "session_id": string;
  "store_seq": number;
};

export type PageKey = {
  "segment_id": string;
  "start_ms": number;
  "track_id": string;
};

export type PeerAnalysisProvenance = {
  "artifact_alias_id": string;
  "event_id": string;
  "owner_device_id": string;
  "public_id": string;
  "revision": Revision;
  "session_id": string;
  "snapshot_id": string;
  "source_cursor": number;
};

export type PeerPublicationBatch = {
  "after_cursor": number;
  "changes": Array<PublicationChange>;
  "cursor": number;
  "event_id": string;
  "owner_device_id": string;
  "session_id": string;
};

export type PeerPublicationSnapshot = {
  "artifacts": Array<PublicArtifact>;
  "cursor": number;
  "event_id": string;
  "owner_device_id": string;
  "session_id": string;
};

export type PeerSession = {
  "event_id": string;
  "owner_device_id": string;
  "room_name": string;
  "session_id": string;
  "title": string;
};

export type PeerSessionState = {
  "cursor": number;
  "last_sync_at_ms"?: number | null;
  "session": PeerSession;
  "stale": boolean;
};

export type Producer = {
  "name": string;
  "run_id": string;
  "seq": number;
};

export type ProducerReconciled = {
  "evidence": ProducerRecoveryEvidence;
  "final_seq": number;
  "producer_run_id": string;
};

export type ProducerReconciledEvent = {
  "event_id": string;
  "message_id": string;
  "payload": ProducerReconciled;
  "producer": Producer;
  "room_id": string;
  "schema_version": 1;
  "session_id": string;
  "type": "session.producer_reconciled";
};

export type ProducerRecoveryEvidence = {
  "capture_manifest_sha256": string;
  "outbox_replayed": boolean;
  "owned_process_exited": boolean;
  "reason": string;
};

export type ProducerSeal = {
  "final_seq": number;
  "producer_run_id": string;
  "segment_ids": Array<string>;
};

export type ProducerSealEvent = {
  "event_id": string;
  "message_id": string;
  "payload": ProducerSeal;
  "producer": Producer;
  "room_id": string;
  "schema_version": 1;
  "session_id": string;
  "type": "session.producer_sealed";
};

export type PublicArtifact = {
  "evidence": Array<PublicEvidence>;
  "kind": AnalysisKind;
  "public_id": string;
  "publication_seq": number;
  "revision": Revision;
  "text": string;
  "title": string;
};

export type PublicEvidence = {
  "public_evidence_id": string;
  "revision": Revision;
  "text": string;
};

export type PublicEvidenceInput = {
  "evidence": AnalysisEvidence;
  "reviewed_text": string;
};

export type PublicSearchHit = {
  "last_sync_at_ms"?: number | null;
  "match_end_utf8": number;
  "match_start_utf8": number;
  "owner_device_id": string;
  "public_id": string;
  "revision": Revision;
  "session_id": string;
  "stale": boolean;
  "text": string;
  "title": string;
};

export type PublicSelection = {
  "owner_device_id": string;
  "public_id": string;
  "revision": Revision;
  "session_id": string;
};

export type PublicSessionView = {
  "artifacts": Array<PublicArtifact>;
  "cursor": number;
  "event_id": string;
  "last_sync_at_ms"?: number | null;
  "local": boolean;
  "owner_device_id": string;
  "room_name": string;
  "session_id": string;
  "stale": boolean;
  "title": string;
};

export type PublicSnapshot = {
  "artifacts": Array<PublicArtifact>;
  "cursor": number;
};

export type PublicationChange = {
  "artifact"?: PublicArtifact | null;
  "public_id": string;
  "publication_seq": number;
  "withdrawn": boolean;
};

export type Receipt = {
  "duplicate": boolean;
  "message_id": string;
  "store_seq": number;
};

export type RecoveryRevision = {
  "next_revision"?: Revision | null;
  "segment_id": string;
  "terminal": boolean;
};

export type RecoverySegment = {
  "audio": AudioRange;
  "next_revision": Revision;
  "previous_status"?: TranscriptStatus | null;
  "reason"?: string | null;
  "recording_ref"?: string | null;
  "segment_id": string;
  "track_id": string;
};

export type Revision = number;

export type RevisionOrigin = {
  "kind": "asr";
} | {
  "file_sha256": string;
  "kind": "legacy_import";
  "line": number;
  "speaker_label"?: string | null;
} | {
  "base_revision": Revision;
  "kind": "human";
  "operator_id": string;
  "reason": string;
};

export type SessionExport = {
  "gaps": Array<AudioGap>;
  "snapshot": SessionSnapshot;
  "sources": Array<SnapshotItem>;
  "status": SessionStatus;
  "translations": Array<TranslationRecord>;
};

export type SessionSnapshot = {
  "cursor": number;
  "incomplete": Array<IncompleteSegment>;
  "session": SessionSpec;
  "transcript": Array<TranscriptRecord>;
};

export type SessionSpec = {
  "event_id": string;
  "owner_device_id": string;
  "room_id": string;
  "session_id": string;
  "title": string;
};

export type SessionState = "created" | "preparing" | "ready" | "recording" | "stopping" | "draining" | "completed" | "interrupted";

export type SessionStatus = {
  "capture_stopped": boolean;
  "direction_epoch": number;
  "incomplete": boolean;
  "session_id": string;
  "state": SessionState;
  "state_seq": number;
  "target_languages": Array<string>;
  "transcript_sealed": boolean;
};

export type SessionSummary = {
  "cursor": number;
  "segment_count": number;
  "session": SessionSpec;
  "status": SessionStatus;
  "translation_pending": number;
};

export type SessionTransition = {
  "expected_state": SessionState;
  "next_state": SessionState;
  "reason": string;
};

export type SessionTransitionEvent = {
  "event_id": string;
  "message_id": string;
  "payload": SessionTransition;
  "producer": Producer;
  "room_id": string;
  "schema_version": 1;
  "session_id": string;
  "type": "session.changed";
};

export type SnapshotItem = {
  "audio": AudioRange;
  "recording_ref"?: string | null;
  "segment_id": string;
  "track_id": string;
  "transcript"?: TranscriptRecord | null;
};

export type SnapshotPage = {
  "cursor": number;
  "items": Array<SnapshotItem>;
  "next_after"?: PageKey | null;
  "session": SessionSpec;
  "status": SessionStatus;
};

export type SourceSpan = {
  "end_utf8": number;
  "quote": string;
  "segment_id": string;
  "segment_revision": Revision;
  "start_utf8": number;
};

export type SpeakerAssignment = {
  "created_at_ms": number;
  "current": boolean;
  "label": SpeakerLabel;
  "origin": SpeakerAssignmentOrigin;
  "revision": Revision;
  "segment_id": string;
  "session_id": string;
  "source_revision": Revision;
};

export type SpeakerAssignmentCommand = {
  "expected_revision"?: Revision | null;
  "label": SpeakerLabel;
  "origin": SpeakerAssignmentOrigin;
  "request_id": string;
  "segment_id": string;
  "session_id": string;
  "source_revision": Revision;
};

export type SpeakerAssignmentOrigin = {
  "kind": "automatic";
  "model_manifest_id": string;
  "model_version": string;
} | {
  "kind": "human";
  "operator_id": string;
  "reason": string;
};

export type SpeakerEmbeddingCommand = {
  "embedding": Array<number>;
  "expected_revision"?: Revision | null;
  "model_manifest_id": string;
  "model_version": string;
  "pcm_sha256": string;
  "request_id": string;
  "segment_id": string;
  "session_id": string;
  "source_revision": Revision;
};

export type SpeakerLabel = {
  "kind": "unknown";
} | {
  "kind": "overlap";
} | {
  "kind": "anonymous";
  "speaker_id": string;
};

export type TrackKind = "mic" | "system" | "room_mix" | "replay" | "legacy_import";

export type TrackSeal = {
  "final_sample": number;
  "segment_ids": Array<string>;
  "track_id": string;
};

export type TrackSpec = {
  "kind": TrackKind;
  "sample_rate": number;
  "session_id": string;
  "track_id": string;
};

export type TranscriptFinal = {
  "audio": AudioRange;
  "backend": string;
  "configured_source_language": string;
  "detected_language"?: string | null;
  "direction_epoch": number;
  "model_manifest_id": string;
  "reason"?: string | null;
  "revision": Revision;
  "segment_id": string;
  "speaker_id"?: string | null;
  "status": TranscriptStatus;
  "target_languages": Array<string>;
  "text": string;
  "track_id": string;
};

export type TranscriptFinalEvent = {
  "event_id": string;
  "message_id": string;
  "payload": TranscriptFinal;
  "producer": Producer;
  "room_id": string;
  "schema_version": 1;
  "session_id": string;
  "type": "transcript.final";
};

export type TranscriptRecord = {
  "created_seq": number;
  "origin": RevisionOrigin;
  "payload": TranscriptFinal;
  "session_id": string;
};

export type TranscriptRevision = {
  "expected_revision": Revision;
  "operator_id": string;
  "reason": string;
  "segment_id": string;
  "text": string;
};

export type TranscriptRevisionEvent = {
  "event_id": string;
  "message_id": string;
  "payload": TranscriptRevision;
  "producer": Producer;
  "room_id": string;
  "schema_version": 1;
  "session_id": string;
  "type": "transcript.revised";
};

export type TranscriptSeal = {
  "capture_manifest_sha256": string;
};

export type TranscriptSealEvent = {
  "event_id": string;
  "message_id": string;
  "payload": TranscriptSeal;
  "producer": Producer;
  "room_id": string;
  "schema_version": 1;
  "session_id": string;
  "type": "session.transcript_sealed";
};

export type TranscriptStatus = "success" | "empty" | "failed";

export type TranslationFailed = {
  "attempt": number;
  "code": string;
  "direction_epoch": number;
  "reason": string;
  "revision": Revision;
  "translation_id": string;
};

export type TranslationFailedEvent = {
  "event_id": string;
  "message_id": string;
  "payload": TranslationFailed;
  "producer": Producer;
  "room_id": string;
  "schema_version": 1;
  "session_id": string;
  "type": "translation.failed";
};

export type TranslationFinal = {
  "attempt": number;
  "backend": string;
  "direction_epoch": number;
  "elapsed_ms": number;
  "model_manifest_id": string;
  "revision": Revision;
  "status": TranslationStatus;
  "text": string;
  "translation_id": string;
};

export type TranslationFinalEvent = {
  "event_id": string;
  "message_id": string;
  "payload": TranslationFinal;
  "producer": Producer;
  "room_id": string;
  "schema_version": 1;
  "session_id": string;
  "type": "translation.final";
};

export type TranslationPage = {
  "cursor": number;
  "items": Array<TranslationRecord>;
  "next_after"?: TranslationPageKey | null;
};

export type TranslationPageKey = {
  "created_seq": number;
  "translation_id": string;
};

export type TranslationRecord = {
  "created_seq": number;
  "error"?: string | null;
  "request": TranslationRequested;
  "result"?: TranslationFinal | null;
  "session_id": string;
  "state": string;
  "text"?: string | null;
  "updated_seq": number;
};

export type TranslationRequested = {
  "attempt": number;
  "backend": string;
  "context_spans"?: Array<SourceSpan>;
  "direction_epoch": number;
  "input_text": string;
  "model_manifest_id": string;
  "normalization_version": string;
  "revision": Revision;
  "source_spans": Array<SourceSpan>;
  "target_language": string;
  "translation_id": string;
};

export type TranslationRequestedEvent = {
  "event_id": string;
  "message_id": string;
  "payload": TranslationRequested;
  "producer": Producer;
  "room_id": string;
  "schema_version": 1;
  "session_id": string;
  "type": "translation.requested";
};

export type TranslationStatus = "final" | "passthrough";

export type TranslationWork = {
  "audio": AudioRange;
  "configured_source_language": string;
  "detected_language"?: string | null;
  "direction_epoch": number;
  "source_span": SourceSpan;
  "target_language": string;
  "track_id": string;
};
