<script lang="ts">
 import {onMount,createEventDispatcher} from 'svelte';
 import {forumClient} from '../lib/forum/factory';
 import {SpeakerClient,speakerText,type SpeakerAssignment,type SpeakerStatus,type SpeakerLabel} from '../lib/forum/speakers';
 import type {MeetingPage} from '../lib/forum/client';
 import {errorText} from '../lib/forum/session-fence';
 export let sessionId:string;export let transcript:MeetingPage|null;export let active=true;
 const dispatch=createEventDispatcher<{assignments:SpeakerAssignment[]}>();const client=new SpeakerClient(forumClient.transport);const writable=forumClient.mode==='desktop';
 let status:SpeakerStatus|null=null;let assignments:SpeakerAssignment[]=[];let busy=false;let reading=false;let destroyed=false;let error='';let modelPath='';let segmentId='';let choice='unknown';let reason='';
 $: segments=(transcript?.items??[]).filter(item=>item.transcript?.payload.status==='success');
 $: current=assignments.find(a=>a.segment_id===segmentId);
 $: source=segments.find(item=>item.segment_id===segmentId)?.transcript;
 $: anonymous=[...new Set(assignments.filter(a=>a.current&&a.label.kind==='anonymous').flatMap(a=>a.label.kind==='anonymous'?[a.label.speaker_id]:[]))];
 $: label=status?.session_id&&status.session_id!==sessionId?'另一场次正在分析':({disabled:'未启用',preparing:'检查模型',waiting:'等待实时任务释放资源',running:'分析已有录音',unavailable:'依赖未就绪',stopping:'正在停止',error:'分析失败',uncontained:'进程尚未停止',stopped:'已停止'}[status?.state??'disabled']??status?.state);
 async function refresh(){if(reading||destroyed||!writable)return;reading=true;try{const next=await client.status();const values=await client.assignments(sessionId);if(!destroyed){status=next;assignments=values;dispatch('assignments',values);}}catch(e){if(!destroyed)error=errorText(e);}finally{reading=false;}}
 async function act(work:()=>Promise<void>){if(!writable||busy)return;busy=true;error='';try{await work();}catch(e){if(!destroyed)error=errorText(e);}finally{if(!destroyed){busy=false;void refresh();}}}
 function enable(){void act(async()=>{const path=modelPath.trim();if(path&&!path.startsWith('/'))throw new Error('请填写本地模型的绝对目录。');status=await client.enable(sessionId,path||null);});}
 function disable(){void act(async()=>{status=await client.disable();});}
 function chooseSegment(){const old=assignments.find(a=>a.segment_id===segmentId&&a.current);choice=old?.label.kind==='anonymous'?old.label.speaker_id:old?.label.kind??'unknown';reason='';}
 function correct(){if(!source)return;const saved=source;const prior=current;const label:SpeakerLabel=choice==='unknown'?{kind:'unknown'}:choice==='overlap'?{kind:'overlap'}:{kind:'anonymous',speaker_id:choice==='new'?crypto.randomUUID():choice};void act(async()=>{const updated=await client.correct({request_id:crypto.randomUUID(),session_id:sessionId,segment_id:saved.payload.segment_id,source_revision:saved.payload.revision,expected_revision:prior?.revision??null,label,origin:{kind:'human',operator_id:'local-operator',reason:reason.trim()}});if(!destroyed){assignments=[...assignments.filter(a=>a.segment_id!==updated.segment_id),updated];dispatch('assignments',assignments);}});}
 onMount(()=>{void refresh();const timer=window.setInterval(()=>{if(active&&!busy)void refresh();},3000);return()=>{destroyed=true;window.clearInterval(timer);};});
</script>
<details class="speaker-panel"><summary>匿名说话人标签 <span>{label??'未启用'}</span></summary><div class="speaker-body"><p>仅对当前场次已有录音进行本地分析。匿名标签不代表实名身份；重叠发言可由操作员标记。</p>{#if status?.notice}<p class="notice">{status.notice}</p>{/if}{#if status}<p>已处理 {status.completed} 段 · 跳过 {status.skipped} 段{status.active_segment?` · 当前 ${status.active_segment.slice(0,8)}`:''}</p>{/if}{#if error}<p class="error" role="alert">{error}</p>{/if}<label>本地 ECAPA 模型目录（可选）<input bind:value={modelPath} placeholder="留空使用应用管理的模型目录" disabled={busy}/></label><div class="actions"><button disabled={!writable||busy||(status?.enabled&&status.session_id===sessionId)} on:click={enable}>启用当前场次分析</button><button disabled={!writable||busy||!status?.enabled} on:click={disable}>停止匿名分析</button></div>
 <fieldset><legend>人工修订当前页的说话人</legend><label>原文片段<select bind:value={segmentId} on:change={chooseSegment}><option value="">选择片段</option>{#each segments as item}<option value={item.segment_id}>{Math.floor(item.audio.start_ms/60000)}:{String(Math.floor(item.audio.start_ms/1000)%60).padStart(2,'0')} · {item.transcript?.payload.text.slice(0,55)}</option>{/each}</select></label>{#if source}<p>{current?`${speakerText(current.label)} · 标签 V${current.revision}${current.current?'':' · 原文已修订，请重核'}`:'暂无标签'} · 原文 V{source.payload.revision}</p><label>新标签<select bind:value={choice}><option value="unknown">说话人未知</option><option value="overlap">重叠发言</option>{#each anonymous as id}<option value={id}>匿名 {id.slice(0,6)}</option>{/each}<option value="new">创建本场新的匿名标签</option></select></label><label>修订依据<input bind:value={reason} maxlength="300" placeholder="例如：已对照此段录音核查"/></label><button disabled={!writable||busy||!reason.trim()} on:click={correct}>保存标签修订</button>{/if}</fieldset></div></details>
<style>
 .speaker-panel{margin:0 0 15px;border:1px solid #dce2eb;background:#f6f8fb}.speaker-panel>summary{cursor:pointer;display:flex;gap:14px;align-items:center;font-size:12px;padding:12px 14px;color:#4d607f}.speaker-panel summary span{margin-left:auto;font-size:10px;color:#8190a6}.speaker-body{padding:4px 14px 18px}.speaker-body>p,fieldset p{font-size:11px;line-height:1.8;color:#7a879b}.notice{background:#eef2f7;padding:8px 10px}.error{color:#a34737!important;background:#ffefeb;padding:8px}label{display:block;font-size:11px;color:#65748b;margin:13px 0}input,select{font:inherit;width:100%;padding:8px;border:1px solid #ccd5e1;border-radius:0;background:white;box-sizing:border-box;margin-top:7px;color:#344563}.actions{display:flex;gap:10px;flex-wrap:wrap}button{font-size:11px;padding:8px 11px;border:1px solid #c5cfdd;background:white;color:#455d82}button:disabled{opacity:.4}fieldset{margin-top:20px;border:1px solid #d7dee8;padding:12px;min-width:0}legend{font-size:11px;color:#6a7b94}
</style>
